### ISSUE TITLE
Hi, I cannot send buffer over 250 bytes... although the xtend manual says the maximum payload size can be upto 2048bytes.

### ISSUE THREAD

**Issue by fvarelie** [rwestlund/node-digimesh#1]

**Comment by rwestlund** [comment]
I need some more information.
1. Can you provide a link to the datasheet you're referencing and the part number you're using?
2. Can you send more than 250 bytes with a different library? The digimesh parts I use have an undocumented limit somewhere around 87 bytes.
3. Is that 250 bytes of payload, or total packet length?
4. Can you send 251 bytes?  There could be a bug in the way I'm bit shifting length that limits it to 256 total bytes.

I'm using a 1024-byte receive buffer, which would need to be increased, but I'm not sure why you're seeing a 250-byte limit.

**Comment by rwestlund** [comment]
Closing due to timeout.
